const plants = [

    { "id": 1, "name": "ต้นออมเงินออมทอง", "cate_id": 1, "image": "image/1.png" },
    { "id": 2, "name": "ต้นนางกวัก", "cate_id": 1, "image": "image/2.png" },
    { "id": 3, "name": "ต้นไผ่กวนอิม", "cate_id": 1, "image": "image/3.png" },
    { "id": 4, "name": "กวักมรกต ", "cate_id": 1, "image": "image/4.png" },
    { "id": 5, "name": "ต้นปีบ", "cate_id": 1, "image": "image/5.png" },
    { "id": 6, "name": "เศรษฐีเรือนใน", "cate_id": 1, "image": "image/6.png" },
    { "id": 7, "name": "ต้นใบเงิน", "cate_id": 1, "image": "image/7.png" },
    { "id": 8, "name": "ต้นวาสนา", "cate_id": 1, "image": "image/8.png" },
    { "id": 9, "name": "ต้นศุภโชค", "cate_id": 1, "image": "image/9.png" },
    { "id": 10, "name": "ว่านรวยล้นฟ้า", "cate_id": 1, "image": "image/10.png" },
    { "id": 11, "name": "ว่านรวยไม่เลิก", "cate_id": 1, "image": "image/11.png" },
    { "id": 12, "name": "ต้นเงินไหลมา ", "cate_id": 1, "image": "image/12.png" },
    { "id": 13, "name": "ต้นนางกวัก ", "cate_id": 1, "image": "image/13.png" },
    { "id": 14, "name": "ยางอินเดีย", "cate_id": 1, "image": "image/14.png" },
    { "id": 15, "name": "พลูด่าง", "cate_id": 1, "image": "image/15.png" },
    { "id": 16, "name": "เฟิร์นข้าหลวง", "cate_id": 1, "image": "image/16.png" },
    { "id": 17, "name": "เงินไหลมา", "cate_id": 1, "image": "image/17.png" },
    { "id": 18, "name": "หมากผู้หมากเมีย", "cate_id": 1, "image": "image/18.png" },
    { "id": 19, "name": "ว่านเสน่ห์จันทร์ขาว", "cate_id": 1, "image": "image/19.png" },
    { "id": 20, "name": "ต้นเศรษฐีรวยทรัพย์ หรือ ต้นเศรษฐีมีทรัพย์", "cate_id": 1, "image": "image/20.png" },
    { "id": 21, "name": "พลูด่าง", "cate_id": 2, "image": "image/1.png" },
    { "id": 22, "name": "ต้นใบเงิน ", "cate_id": 2, "image": "image/2.png" },
    { "id": 23, "name": "ต้นไผ่กวนอิม", "cate_id": 2, "image": "image/3.png" },
    { "id": 24, "name": "ลิ้นมังกรแคระ", "cate_id": 2, "image": "image/4.png" },
    { "id": 25, "name": "ออมเงิน ออมทอง", "cate_id": 2, "image": "image/5.png" },
    { "id": 26, "name": "สับปะรดสี", "cate_id": 2, "image": "image/6.png" },
    { "id": 27, "name": "ต้นแก้วแคระ", "cate_id": 2, "image": "image/7.png" },
    { "id": 28, "name": "พลูงาช้าง", "cate_id": 2, "image": "image/8.png" },
    { "id": 29, "name": "กวักมรกต", "cate_id": 2, "image": "image/9.png" },
    { "id": 30, "name": "แก้วกาญจนา หรือ อโกลนีมา", "cate_id": 2, "image": "image/10.png" },
    { "id": 31, "name": "ต้นไผ่กวนอิม", "cate_id": 2, "image": "image/11.png" },
    { "id": 32, "name": "พลูฉลุ", "cate_id": 2, "image": "image/12.png" },
    { "id": 33, "name": "ต้นวาสนา", "cate_id": 2, "image": "image/13.png" },
    { "id": 34, "name": "ลิ้นมังกร ", "cate_id": 2, "image": "image/14.png" },
    { "id": 35, "name": "พลูทอง", "cate_id": 2, "image": "image/15.png" },
    { "id": 36, "name": "ต้นนางกวัก ", "cate_id": 2, "image": "image/16.png" },
    { "id": 37, "name": "หัวใจทศกัณฑ์ หรือ โฮย่า", "cate_id": 2, "image": "image/17.png" },
    { "id": 38, "name": "ต้นบารมีเศรษฐี", "cate_id": 2, "image": "image/18.png" },
    { "id": 39, "name": "ดอกหน้าวัว", "cate_id": 2, "image": "image/19.png" },
    { "id": 40, "name": "ยางอินเดีย", "cate_id": 2, "image": "image/20.png" },
    { "id": 41, "name": "สับปะรดสี", "cate_id": 3, "image": "image/1.png" },
    { "id": 42, "name": "พลูทอง", "cate_id": 3, "image": "image/2.png" },
    { "id": 43, "name": "แก้วกาญจนา หลักทรัพย์", "cate_id": 3, "image": "image/3.png" },
    { "id": 44, "name": "ว่านเสน่ห์กาหลง", "cate_id": 3, "image": "image/4.png" },
    { "id": 45, "name": "วาเลนไทน์ หรือ อโกลนีมา", "cate_id": 3, "image": "image/5.png" },
    { "id": 46, "name": "มะลิ", "cate_id": 3, "image": "image/6.png" },
    { "id": 47, "name": "กุหลาบแดง", "cate_id": 3, "image": "image/7.png" },
    { "id": 48, "name": "ดอกรัก", "cate_id": 3, "image": "image/8.png" },
    { "id": 49, "name": "เฟิร์นข้าหลวง", "cate_id": 3, "image": "image/9.png" },
    { "id": 50, "name": "กวักมรกต", "cate_id": 3, "image": "image/10.png" },
    { "id": 51, "name": "กล้วยไม้", "cate_id": 3, "image": "image/11.png" },
    { "id": 52, "name": " ต้นวาสนา", "cate_id": 3, "image": "image/12.png" },
    { "id": 53, "name": "เปปเปอร์โรเมียลายแตงโม", "cate_id": 3, "image": "image/13.png" },
    { "id": 54, "name": "ไพเลีย", "cate_id": 3, "image": "image/14.png" },
    { "id": 55, "name": "ว่านเสน่ห์จันทร์ขาว", "cate_id": 3, "image": "image/15.png" },
    { "id": 56, "name": "บีโกเนีย", "cate_id": 3, "image": "image/16.png" },
    { "id": 57, "name": "ว่านเสน่ห์กวักแม่ทองใบ", "cate_id": 3, "image": "image/17.png" },
    { "id": 58, "name": "บัว", "cate_id": 3, "image": "image/18.png" },
    { "id": 59, "name": "ต้นสาลิกาลิ้นทอง", "cate_id": 3, "image": "image/19.png" },
    { "id": 60, "name": "มรกตแดง", "cate_id": 3, "image": "image/20.png" },
    { "id": 61, "name": "ตีนตุ๊กแก", "cate_id": 4, "image": "image/1.png" },
    { "id": 62, "name": "เดหลี", "cate_id": 4, "image": "image/2.png" },
    { "id": 63, "name": "เขียวหมื่นปี", "cate_id": 4, "image": "image/3.png" },
    { "id": 64, "name": "ยางอินเดีย", "cate_id": 4, "image": "image/4.png" },
    { "id": 65, "name": "เสน่ห์จันทร์แดง", "cate_id": 4, "image": "image/5.png" },
    { "id": 66, "name": "ว่านนางคุ้ม", "cate_id": 4, "image": "image/6.png" },
    { "id": 67, "name": "ลิ้นมังกรแคระ", "cate_id": 4, "image": "image/7.png" },
    { "id": 68, "name": "เศรษฐีเรือนใน ", "cate_id": 4, "image": "image/8.png" },
    { "id": 69, "name": "พลูด่าง", "cate_id": 4, "image": "image/9.png" },
    { "id": 70, "name": "วักมรกต", "cate_id": 4, "image": "image/10.png" },
    { "id": 71, "name": "ปาล์มสิบสองปันนา", "cate_id": 4, "image": "image/11.png" },
    { "id": 72, "name": "วาสนา", "cate_id": 4, "image": "image/12.png" },
    { "id": 73, "name": "สารภี", "cate_id": 4, "image": "image/13.png" },
    { "id": 74, "name": "พุด", "cate_id": 4, "image": "image/14.png" },
    { "id": 75, "name": "ต้นสน", "cate_id": 4, "image": "image/15.png" },
    { "id": 76, "name": "ลิ้นมังกรแคระขอบทอง", "cate_id": 4, "image": "image/16.png" },
    { "id": 77, "name": "เปเปอร์โรเมียด่าง", "cate_id": 4, "image": "image/17.png" },
    { "id": 78, "name": "พลูด่าง", "cate_id": 4, "image": "image/18.png" },
    { "id": 79, "name": "ต้นใบเงิน", "cate_id": 4, "image": "image/19.png" },
    { "id": 80, "name": "ต้นไผ่กวนอิม", "cate_id": 4, "image": "image/20.png" },
    { "id": 81, "name": "ออมเพชร", "cate_id": 5, "image": "image/1.png" },
    { "id": 82, "name": "ฟิโลเดนดรอน มรกตหยก", "cate_id": 5, "image": "image/2.png" },
    { "id": 83, "name": "เศรษฐีเรือนนอก", "cate_id": 5, "image": "image/3.png" },
    { "id": 84, "name": "รวยไม่เลิก", "cate_id": 5, "image": "image/4.png" },
    { "id": 85, "name": "บอนไซจิ๋ว", "cate_id": 5, "image": "image/5.png" },
    { "id": 86, "name": "เสน่ห์จันทร์ขาว", "cate_id": 5, "image": "image/6.png" },
    { "id": 87, "name": "หมากผู้หมากเมีย", "cate_id": 5, "image": "image/7.png" },
    { "id": 88, "name": "ต้นเงินไหลมา", "cate_id": 5, "image": "image/8.png" },
    { "id": 89, "name": "เสน่ห์จันทร์แดง", "cate_id": 5, "image": "image/9.png" },
    { "id": 90, "name": "ต้นไผ่กวนอิม", "cate_id": 5, "image": "image/10.png" },
    { "id": 91, "name": "พลูด่าง", "cate_id": 5, "image": "image/11.png" },
    { "id": 92, "name": "ต้นนางกวัก", "cate_id": 5, "image": "image/12.png" },
    { "id": 93, "name": "ต้นออมเงินออมทองแคระ", "cate_id": 5, "image": "image/13.png" },
    { "id": 94, "name": "กวักมรกต", "cate_id": 5, "image": "image/14.png" },
    { "id": 95, "name": "เศรษฐีเรือนใน ", "cate_id": 5, "image": "image/15.png" },
    { "id": 96, "name": "กวนอิมเงิน", "cate_id": 5, "image": "image/16.png" },
    { "id": 97, "name": "กวนอิมทอง", "cate_id": 5, "image": "image/17.png" },
    { "id": 98, "name": "ต้นใบเงิน", "cate_id": 5, "image": "image/18.png" },
    { "id": 99, "name": "ต้นว่านมหาลาภ", "cate_id": 5, "image": "image/19.png" },
    { "id": 100, "name": "ว่านรวยไม่เลิก", "cate_id": 5, "image": "image/20.png" }
    
]